### ISSUE TITLE
Robot does not move

### ISSUE THREAD

**Issue by SaengthongStk** [ros-industrial/abb_driver#10]
I'm using [ABB experimental package](https://github.com/ros-industrial/abb_experimental) with RobotStudio and ROS-kinetic. I followed these [tutorials](http://wiki.ros.org/action/show/abb_driver/Tutorials?action=show&redirect=abb%2FTutorials) to configure ROS and an ABB IRB1200 robot in RobotStudio to work together. When launching the moveit_planning_execution.launch in a terminal that's shown below.

`$ roslaunch abb_irb1200_5_90_moveit_config moveit_planing_execution.launch sim:=false robot_ip:=192.168.1.1`

I get the following error when I start plan and execute :

```
[ERROR] [1610335075.542277098]: Controller is taking too long to execute trajectory (the expected upper bound for the trajectory execution was 3.590049 seconds). Stopping trajectory.
```
I tried 2 things in [trajectory_execution.launch.xml](https://github.com/ros-industrial/abb_experimental/blob/kinetic-devel/abb_irb1200_5_90_moveit_config/launch/trajectory_execution.launch.xml) without success:

1. Edit the following value from 1.2 to 3.2:
`<param name="trajectory_execution/allowed_execution_duration_scaling" value="3.2"/> <!-- default 1.2 -->`

The result is it takes a longer time to show the same error.

2. Add the following  parameter:
`<param name="trajectory_execution/execution_duration_monitoring" value="false"/>`

The result is it took too long to execute without showing any output on the terminal, I have waited for 3 hours before closing it.

What am I doing wrong?

**Comment by SaengthongStk** [comment]
Thank you for replying.

> Does your IRB 1200 not move at all, or does it never complete the motion?

It doesn't move at all. The following picture is the outputs from the pendant.

![RS_01](https://user-images.githubusercontent.com/77257389/104162293-e9a00180-5426-11eb-9f0c-cb9aa0a23a03.jpg)

By the way I think it's correctly connected because I set manual mode then jock the robot from RobotStudio and the real robot in RViz can move along.

**Comment by gavanderhoorn** [comment]
Is the motion task running? Without that task, the robot will not move.

See [wiki/abb_driver/Tutorials/RunServer - Robot Motion Task](http://wiki.ros.org/abb_driver/Tutorials/RunServer#Robot_Motion_Task).

For now this doesn't seem to have anything to do with trajectory execution monitor.

**Comment by gavanderhoorn** [comment]
I've updated the title of your issue, as that's what you observe: your robot does not move.

We don't want to prematurely focus on MoveIt, or on work-arounds for the TEM.

**Comment by SaengthongStk** [comment]
> Is the motion task running? Without that task, the robot will not move.

I'm not sure, Do I have to check here?

![image](https://user-images.githubusercontent.com/77257389/104166294-27078d80-542d-11eb-8c61-34ce0e8f7cff.png)

The pointer doesn't move any where all the time.

**Comment by gavanderhoorn** [comment]
Have you followed the steps described in [wiki/abb_driver/Tutorials/RunServer - Robot Motion Task](http://wiki.ros.org/abb_driver/Tutorials/RunServer#Robot_Motion_Task)?

**Comment by SaengthongStk** [comment]
> Have you followed the steps described in [wiki/abb_driver/Tutorials/RunServer - Robot Motion Task](http://wiki.ros.org/abb_driver/Tutorials/RunServer#Robot_Motion_Task)?

Yes, And I also ran in both MANUAL mode and AUTO mode.

**Comment by gavanderhoorn** [comment]
Your first screenshot is a typical example of everything running except the motion task.

Can you show a screenshot of the *production window* on the virtual TP after you've started the motion task?

And can you also verify you have the [tasks configured correctly](http://wiki.ros.org/abb_driver/Tutorials/InstallServer#Create_Tasks)?

**Comment by SaengthongStk** [comment]
![image](https://user-images.githubusercontent.com/77257389/104257307-afc70d80-54af-11eb-9d06-458e83347265.png)

![image](https://user-images.githubusercontent.com/77257389/104257377-dc7b2500-54af-11eb-8976-c6cf1af5da1b.png)

I'm not sure about setting motion task, I can't configure the motion task both ROS_MotionServer and Ros_StateServer as you can see the following picture. 

![image](https://user-images.githubusercontent.com/77257389/104257793-ccb01080-54b0-11eb-9fb9-91ba4a0b25fc.png)

But in this [tutorial](http://wiki.ros.org/abb_driver/Tutorials/InstallServer) ,We have to configure the motion task to "NO".

![image](https://user-images.githubusercontent.com/77257389/104257908-0f71e880-54b1-11eb-8f95-28fd4169dc40.png)

**Comment by gavanderhoorn** [comment]
The `ROS_MotionServer` is not the motion task. `ROS_motion.mod` contains the main code for the motion task.

It looks like you didn't configure `T_ROB1` correctly, and the code shown is the default code, which is not part of the driver.

That's the reason your robot isn't moving.

You'll either want to remove your current main module, or overwrite whatever you have now with the code in `ROS_motion.mod`.

See also the second note right under the table in section `3.2` you show in your screenshot:

> If `T_ROB1` has existing motion-control modules, you may need to rename the `main()` routine in `ROS_Motion.mod` to `ROS_main()`. In this case, set the *Entry point* for `T_ROB1` task to `ROS_main()`.

**Comment by gavanderhoorn** [comment]
As this doesn't appear to be a problem with the code, but with the configuration of your robot controller, I'm going to close this issue.

That does not mean I'm dismissing your problem, only that we want to keep the issue tracker for reporting problems with the driver itself.

Feel free to keep commenting on the issue of course.

**Comment by SaengthongStk** [comment]
It works now. Thanks for your help. You help me a lot.

**Comment by zp2546265641** [comment]
> As this doesn't appear to be a problem with the code, but with the configuration of your robot controller, I'm going to close this issue.
> 
> That does not mean I'm dismissing your problem, only that we want to keep the issue tracker for reporting problems with the driver itself.
> 
> Feel free to keep commenting on the issue of course.

Hello, my robot arm has the same problem. Could you help me take a look? What other information do I need to provide?

**Comment by zp2546265641** [comment]
> As this doesn't appear to be a problem with the code, but with the configuration of your robot controller, I'm going to close this issue.
> 
> That does not mean I'm dismissing your problem, only that we want to keep the issue tracker for reporting problems with the driver itself.
> 
> Feel free to keep commenting on the issue of course.

<img width="504" height="990" alt="Image" src="https://github.com/user-attachments/assets/a62ff2ad-60ed-41be-96c1-b8ca932846ef" />

<img width="2025" height="457" alt="Image" src="https://github.com/user-attachments/assets/2afaa92f-add1-4f86-b03f-62ada0b1fa46" />

<img width="1254" height="895" alt="Image" src="https://github.com/user-attachments/assets/346e5a67-3bdf-4a68-93dc-01605d763d47" />
