### ISSUE TITLE
Publishing to `robot_status` topic

### ISSUE THREAD

**Issue by MHashmi2018** [ros-industrial/abb_driver#11]
I have studies this driver and I have not yet confirmed if it subscribes to the `robot_status` topic of type `industrial_msgs/RobotStatus`. Can someone please confirm for me if this is the case? I would like to be absolutely sure before I run anything on the real robot.

**Comment by gavanderhoorn** [comment]
> I have not yet confirmed if it subscribes to the `robot_status` topic

no, the driver does not *subscribe* to `robot_status`.

It does *publish* to it though.

Refer to [wiki/abb_driver: Published_Topics](http://wiki.ros.org/abb_driver#Published_Topics).

For the RAPID side:

https://github.com/ros-industrial/abb_driver/blob/ddf8d525a54300374171064b805907f146a40024/rapid/ROS_stateServer.mod#L87-L161

**Comment by gavanderhoorn** [comment]
Closing as I believe the initial question was answered.

**Comment by MHashmi2018** [comment]
Thank you very much!
